### PR TITLE
DOCSP-27817 manual tagging for app-services repo

### PR DESCRIPTION
**Pull request by sarahemlin**
@jwilliams-mongo - there was only one page to be manually tagged and it has the correct spacing & facet syntax. ;)

Please merge when you have a moment!

Thank you!
Sarah

### Jira

- https://jira.mongodb.org/browse/DOCSP-27817

### CODE REVIEW

**Comment by jwilliams-mongo** [comment]
I'll defer to @nlarew on this one as it's an app services repo

**Comment by sarahemlin** [comment]
@dacharyc has been helping me on Realm stuff and has the backstory on the tagging; I was in an Atlas zone since that's the original URL in the top 250 that's redirecting over here.

**Review by dacharyc — COMMENTED** [review]
The only thing I have a question about here is the "tutorial" genre. How was this value selected, @sarahemlin ? This docs section contains a mix of task-based and reference information, so I'm uncertain if the "tutorial" genre applies here - it would help to know the criteria we're using for "tutorial."

**Comment by sarahemlin** [comment]
Hey @dacharyc - the values were all approved by the Docs Leads.  I'm making plans now to visit each team and go through the tagging criteria so the whole team is on the same page; starting with the cloud folks next week in SF.

**Review by dacharyc — APPROVED** [review]
Alrighty, this looks good. Thanks!

**Pull request merged**
